global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'skip-select'
    static_configs:
      - targets: ['skip-select:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'mock-cosmoshub'
    static_configs:
      - targets: ['mock-cosmoshub:26660']
    metrics_path: '/metrics'

  - job_name: 'mock-osmosis'
    static_configs:
      - targets: ['mock-osmosis:26660']
    metrics_path: '/metrics'
